services:
  scheduler-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB} 

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} 
    volumes:
      - schedulerdb2:/var/lib/postgresql/data  
    ports:
      - "2005:5432"  
    restart: always 

volumes:
  schedulerdb2:


