apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  labels:
    app: scc
spec:
  replicas: 0
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      containers:
        - name: scc
          image: lmtp/scheduler-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 90
