apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSmw0R2kwV1YyS1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1URXhPRE13TkRWYUZ3MHpOREV4TURreE9ETTFORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLM3ZKV0k3QWhMZ0JyaWNLUGF6RDVZd0Vlbm1tK2ozbUpIcDQ5VFBFRUJzVWFlaVNadnZtVlRtckQKM2E2RkhSS0Uva0ROVTlMR2NyN3NYK2t3UGZJTG9Fa3FqNDZCK3BYeGMzQ0h4UExxclpva0NHYnVVNmM5VGlqdgp0ZUcyZDM1QlFlRFQ5ZUh3TVFaUEVvcy83WDl3aXZETEc2RHV5U3MvY3ZsREY1TU9lYUt2UzR5YnpDQnJmZFd1CjV5THdqek1XQWNieDc1NjZ5RUJMbWkzNnVHQUQ0Q24wMXU0U25od1MvbjUvK1BMQkdHQ1BHQTU4MERCdUp0K0oKbHkvcUgyUFR5T1hQb2FBeitHNWhBdjhJR0d1QUdCb2RHbkFnWFVwbmp3MzMwWlVwMjFXZ09HYzRuU0Q0S2NmUApBczg1UVRTdC9LWWRFWnNCclJJWERhTTBlaE5OQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaTZLY1Q1bXV1TnZSUlk4TWVEQVBpUkFvQlVEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVE1MmZ2VGZLRgpsUDFubS9lenFITWtleG9HckdLUzZ6aDBySDdVTU9yMnVtR0Z0U1U3SUo0bEhFbk9pK25xYkI5N2tCenkvd3VnCjZvc3NIVVpJU2VoQjBISEtJc0Z4NHRvdWdKVzZaQkJXbnNtSXpmVzlUTnk3U0NzU2FPbzI0aTNGK0dwN0JyQ2wKQU4vM3UxaVpBd0duV01Ed283WXNiSjQ4SlQ3Q1NkRUswOUtZSHhYeEx0R2l0QjRKU1dPcUhka3ZieWg4K2t4bwptd1dFYXMxeDllNG1KWEVQQUNrVDNjb3ZGQW0xZjE4eG5VZWZJcDVKWlhPMmJtbDFxU1ZjSkI1SFprZkcxcUFDCnh6MVM5TmRYUkcxNThOVHF5dnd4Nm1kd2ZvbUU1TEVRcDBGNTNBWU9NaElQS21QelFyK1U5MzRsVkVNeldmRkkKRDNyTDluVGp5dFl2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://1971d6ef-60f5-4c20-a86c-c2ebb39cb284.es-mad-1-gw.linodelke.net:443
  name: lke265313

contexts:
- context:
    cluster: lke265313
    user: lke265313-admin
  name: lke265313-ctx

current-context: lke265313-ctx
