kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-app
  namespace: default
  generation: 1
  labels:
    k8s-app: test-app
  annotations:
    deployment.kubernetes.io/revision: '1'

spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: test-app
  template:
    metadata:
      name: test-app
      # creationTimestamp: null
      labels:
        k8s-app: test-app
    spec:
      containers:
        - name: test-app
          image: lmtp/scheduler-auth
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
status:
  observedGeneration: 1
  replicas: 3
  updatedReplicas: 3
  unavailableReplicas: 3


